// <auto-generated />
using System;
using GoldPC.ServicesService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GoldPC.ServicesService.Migrations
{
    [DbContext(typeof(ServicesDbContext))]
    partial class ServicesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GoldPC.ServicesService.Entities.ServicePart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("ServiceRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_request_id");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("ServiceRequestId");

                    b.ToTable("service_parts", (string)null);
                });

            modelBuilder.Entity("GoldPC.ServicesService.Entities.ServiceRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("ActualCost")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("actual_cost");

                    b.Property<Guid?>("MasterId")
                        .HasColumnType("uuid")
                        .HasColumnName("master_id");

                    b.Property<string>("MasterComment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("master_comment");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("DeviceModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_model");

                    b.Property<decimal>("EstimatedCost")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("estimated_cost");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("request_number");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("serial_number");

                    b.Property<Guid>("ServiceTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_type_id");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("RequestNumber")
                        .IsUnique();

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("service_requests", (string)null);
                });

            modelBuilder.Entity("GoldPC.ServicesService.Entities.ServiceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("base_price");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_duration_minutes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("service_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            BasePrice = 30.00m,
                            Description = "Диагностика и ремонт настольных ПК любой сложности. Замена компонентов, устранение перегрева, восстановление после залития.",
                            EstimatedDurationMinutes = 120,
                            IsActive = true,
                            Name = "Ремонт компьютеров"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            BasePrice = 40.00m,
                            Description = "Ремонт материнских плат, замена матриц, клавиатур, аккумуляторов. Работаем со всеми брендами.",
                            EstimatedDurationMinutes = 180,
                            IsActive = true,
                            Name = "Ремонт ноутбуков"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            BasePrice = 25.00m,
                            Description = "Апгрейд процессора, видеокарты, оперативной памяти, SSD. Подберём совместимые компоненты под ваш бюджет.",
                            EstimatedDurationMinutes = 60,
                            IsActive = true,
                            Name = "Модернизация ПК"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            BasePrice = 15.00m,
                            Description = "Полная аппаратная и программная диагностика. Определим причину неисправности и предложим варианты ремонта.",
                            EstimatedDurationMinutes = 90,
                            IsActive = true,
                            Name = "Диагностика"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            BasePrice = 50.00m,
                            Description = "Подбор комплектующих и профессиональная сборка компьютера под ваши задачи: игры, работа, стриминг.",
                            EstimatedDurationMinutes = 120,
                            IsActive = true,
                            Name = "Сборка ПК на заказ"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            BasePrice = 45.00m,
                            Description = "Восстановление удалённых файлов, данных с повреждённых HDD/SSD, флешек и карт памяти.",
                            EstimatedDurationMinutes = 240,
                            IsActive = true,
                            Name = "Восстановление данных"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            BasePrice = 20.00m,
                            Description = "Чистка от пыли, замена термопасты, профилактика системы охлаждения. Продлим жизнь вашему ПК.",
                            EstimatedDurationMinutes = 90,
                            IsActive = true,
                            Name = "Чистка и обслуживание"
                        });
                });

            modelBuilder.Entity("GoldPC.ServicesService.Entities.WorkReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("new_status");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("previous_status");

                    b.Property<Guid>("ServiceRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_request_id");

                    b.HasKey("Id");

                    b.HasIndex("ServiceRequestId");

                    b.ToTable("work_reports", (string)null);
                });

            modelBuilder.Entity("GoldPC.ServicesService.Entities.ServicePart", b =>
                {
                    b.HasOne("GoldPC.ServicesService.Entities.ServiceRequest", "ServiceRequest")
                        .WithMany("ServiceParts")
                        .HasForeignKey("ServiceRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceRequest");
                });

            modelBuilder.Entity("GoldPC.ServicesService.Entities.ServiceRequest", b =>
                {
                    b.HasOne("GoldPC.ServicesService.Entities.ServiceType", "ServiceType")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("ServiceTypeId")
                        .IsRequired();

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("GoldPC.ServicesService.Entities.WorkReport", b =>
                {
                    b.HasOne("GoldPC.ServicesService.Entities.ServiceRequest", "ServiceRequest")
                        .WithMany("WorkReports")
                        .HasForeignKey("ServiceRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceRequest");
                });

            modelBuilder.Entity("GoldPC.ServicesService.Entities.ServiceRequest", b =>
                {
                    b.Navigation("ServiceParts");
                    b.Navigation("ServiceType");
                    b.Navigation("WorkReports");
                });

            modelBuilder.Entity("GoldPC.ServicesService.Entities.ServiceType", b =>
                {
                    b.Navigation("ServiceRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
