// <auto-generated />
using System;
using System.Collections.Generic;
using CatalogService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CatalogService.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260321135704_AddXCoreGpuFilterAttributes")]
    partial class AddXCoreGpuFilterAttributes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CatalogService.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ComponentType")
                        .HasColumnType("integer")
                        .HasColumnName("component_type");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            ComponentType = 1,
                            Name = "Процессоры",
                            Order = 0,
                            Slug = "processors"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            ComponentType = 2,
                            Name = "Материнские платы",
                            Order = 0,
                            Slug = "motherboards"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            ComponentType = 3,
                            Name = "Оперативная память",
                            Order = 0,
                            Slug = "ram"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            ComponentType = 4,
                            Name = "Видеокарты",
                            Order = 0,
                            Slug = "gpu"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            ComponentType = 5,
                            Name = "Блоки питания",
                            Order = 0,
                            Slug = "psu"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            ComponentType = 6,
                            Name = "Накопители",
                            Order = 0,
                            Slug = "storage"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            ComponentType = 7,
                            Name = "Корпуса",
                            Order = 0,
                            Slug = "cases"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            ComponentType = 8,
                            Name = "Системы охлаждения",
                            Order = 0,
                            Slug = "coolers"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            ComponentType = 9,
                            Name = "Периферия",
                            Order = 0,
                            Slug = "periphery"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000000a"),
                            ComponentType = 10,
                            Name = "Мониторы",
                            Order = 0,
                            Slug = "monitors"
                        });
                });

            modelBuilder.Entity("CatalogService.Models.CategoryFilterAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttributeKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("attribute_key");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<int>("FilterType")
                        .HasColumnType("integer")
                        .HasColumnName("filter_type");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("category_filter_attributes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            AttributeKey = "vram",
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000004"),
                            DisplayName = "Объём видеопамяти",
                            FilterType = 0,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            AttributeKey = "gpu",
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000004"),
                            DisplayName = "Серия GPU",
                            FilterType = 0,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            AttributeKey = "socket",
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000001"),
                            DisplayName = "Сокет",
                            FilterType = 0,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            AttributeKey = "cores",
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000001"),
                            DisplayName = "Количество ядер",
                            FilterType = 1,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            AttributeKey = "socket",
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000002"),
                            DisplayName = "Сокет",
                            FilterType = 0,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            AttributeKey = "chipset",
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000002"),
                            DisplayName = "Чипсет",
                            FilterType = 0,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000007"),
                            AttributeKey = "type",
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000003"),
                            DisplayName = "Тип памяти",
                            FilterType = 0,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000008"),
                            AttributeKey = "capacity",
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000003"),
                            DisplayName = "Объём",
                            FilterType = 0,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000009"),
                            AttributeKey = "capacity",
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000006"),
                            DisplayName = "Объём",
                            FilterType = 0,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-00000000000a"),
                            AttributeKey = "wattage",
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000005"),
                            DisplayName = "Мощность",
                            FilterType = 0,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-00000000000b"),
                            AttributeKey = "efficiency",
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000005"),
                            DisplayName = "Сертификат",
                            FilterType = 0,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-00000000000c"),
                            AttributeKey = "form_factor",
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000007"),
                            DisplayName = "Форм-фактор",
                            FilterType = 0,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-00000000000d"),
                            AttributeKey = "color",
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000007"),
                            DisplayName = "Цвет",
                            FilterType = 0,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-00000000000e"),
                            AttributeKey = "type",
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000008"),
                            DisplayName = "Тип",
                            FilterType = 0,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-00000000000f"),
                            AttributeKey = "socket",
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000008"),
                            DisplayName = "Сокет",
                            FilterType = 0,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000010"),
                            AttributeKey = "tdp",
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000008"),
                            DisplayName = "TDP, Вт",
                            FilterType = 1,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000011"),
                            AttributeKey = "diagonal",
                            CategoryId = new Guid("00000000-0000-0000-0000-00000000000a"),
                            DisplayName = "Диагональ",
                            FilterType = 0,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000012"),
                            AttributeKey = "resolution",
                            CategoryId = new Guid("00000000-0000-0000-0000-00000000000a"),
                            DisplayName = "Разрешение",
                            FilterType = 0,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000013"),
                            AttributeKey = "refresh_rate",
                            CategoryId = new Guid("00000000-0000-0000-0000-00000000000a"),
                            DisplayName = "Частота обновления",
                            FilterType = 0,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000014"),
                            AttributeKey = "type",
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000009"),
                            DisplayName = "Тип устройства",
                            FilterType = 0,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000015"),
                            AttributeKey = "connection",
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000009"),
                            DisplayName = "Подключение",
                            FilterType = 0,
                            SortOrder = 2
                        });
                });

            modelBuilder.Entity("CatalogService.Models.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("country");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("manufacturers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Country = "USA",
                            Name = "Intel"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Country = "USA",
                            Name = "AMD"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Country = "Taiwan",
                            Name = "ASUS"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Country = "Taiwan",
                            Name = "MSI"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Country = "Taiwan",
                            Name = "Gigabyte"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Country = "Taiwan",
                            Name = "ASRock"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Country = "USA",
                            Name = "NVIDIA"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            Country = "Taiwan",
                            Name = "Palit"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            Country = "USA",
                            Name = "Kingston"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            Country = "USA",
                            Name = "Corsair"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            Country = "Taiwan",
                            Name = "G.Skill"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            Country = "Germany",
                            Name = "be quiet!"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000013"),
                            Country = "Taiwan",
                            Name = "Seasonic"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000014"),
                            Country = "South Korea",
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000015"),
                            Country = "USA",
                            Name = "Western Digital"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000016"),
                            Country = "USA",
                            Name = "NZXT"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000017"),
                            Country = "Sweden",
                            Name = "Fractal Design"
                        });
                });

            modelBuilder.Entity("CatalogService.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<double>("Rating")
                        .HasPrecision(3, 2)
                        .HasColumnType("double precision")
                        .HasColumnName("rating");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer")
                        .HasColumnName("review_count");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("source_url");

                    b.Property<Dictionary<string, object>>("Specifications")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("specifications");

                    b.Property<int>("Stock")
                        .HasColumnType("integer")
                        .HasColumnName("stock");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("WarrantyMonths")
                        .HasColumnType("integer")
                        .HasColumnName("warranty_months");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasFilter("external_id IS NOT NULL");

                    b.HasIndex("IsActive");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("Price");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Процессор AMD Ryzen 5 5600X, 6 ядер, 12 потоков, базовая частота 3.7 ГГц, турбо до 4.6 ГГц. Socket AM4. Отличное соотношение цена/производительность для игр и работы.",
                            IsActive = true,
                            IsFeatured = true,
                            ManufacturerId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "AMD Ryzen 5 5600X",
                            Price = 549.00m,
                            Rating = 4.7999999999999998,
                            ReviewCount = 156,
                            Sku = "CPU-AMD-5600X",
                            Specifications = new Dictionary<string, object> { ["socket"] = "AM4", ["cores"] = 6, ["threads"] = 12, ["base_clock"] = "3.7 GHz", ["boost_clock"] = "4.6 GHz", ["tdp"] = "65W", ["l3_cache"] = "32MB", ["unlocked"] = true, ["integrated_graphics"] = false },
                            Stock = 25,
                            WarrantyMonths = 36
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Лучший игровой процессор с технологией 3D V-Cache. 8 ядер, 16 потоков, Socket AM5. Идеален для игр с объёмным кэшем 104MB.",
                            IsActive = true,
                            IsFeatured = true,
                            ManufacturerId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "AMD Ryzen 7 7800X3D",
                            Price = 1299.00m,
                            Rating = 4.9000000000000004,
                            ReviewCount = 89,
                            Sku = "CPU-AMD-7800X3D",
                            Specifications = new Dictionary<string, object> { ["socket"] = "AM5", ["cores"] = 8, ["threads"] = 16, ["base_clock"] = "4.2 GHz", ["boost_clock"] = "5.0 GHz", ["tdp"] = "120W", ["l3_cache"] = "104MB", ["unlocked"] = true, ["integrated_graphics"] = true },
                            Stock = 12,
                            WarrantyMonths = 36
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Процессор Intel Core i5 13-го поколения, 14 ядер (6P+8E), 20 потоков. Socket LGA1700. Отличная производительность для игр и контента.",
                            IsActive = true,
                            IsFeatured = false,
                            ManufacturerId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Intel Core i5-13600KF",
                            OldPrice = 849.00m,
                            Price = 749.00m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 134,
                            Sku = "CPU-INT-13600KF",
                            Specifications = new Dictionary<string, object> { ["socket"] = "LGA1700", ["cores"] = 14, ["threads"] = 20, ["base_clock"] = "3.5 GHz", ["boost_clock"] = "5.1 GHz", ["tdp"] = "125W", ["l3_cache"] = "24MB", ["unlocked"] = true, ["integrated_graphics"] = false },
                            Stock = 18,
                            WarrantyMonths = 36
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Материнская плата ASUS TUF Gaming на чипсете B650, Socket AM5. Поддержка DDR5, PCIe 5.0, WiFi 6, 2.5G LAN. Надёжность военного класса.",
                            IsActive = true,
                            IsFeatured = true,
                            ManufacturerId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Name = "ASUS TUF Gaming B650-Plus WiFi",
                            Price = 429.00m,
                            Rating = 4.5999999999999996,
                            ReviewCount = 67,
                            Sku = "MB-ASUS-B650TUF",
                            Specifications = new Dictionary<string, object> { ["socket"] = "AM5", ["chipset"] = "B650", ["form_factor"] = "ATX", ["memory_slots"] = 4, ["max_memory"] = "128GB", ["memory_type"] = "DDR5", ["pcie_slots"] = "1x PCIe 5.0 x16, 1x PCIe 4.0 x16", ["m2_slots"] = 3, ["usb_ports"] = "8x USB-A, 2x USB-C", ["wifi"] = "WiFi 6", ["lan"] = "2.5G" },
                            Stock = 15,
                            WarrantyMonths = 36
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Материнская плата MSI MAG B650 Tomahawk, Socket AM5. DDR5, PCIe 4.0, WiFi 6E, 2.5G LAN. Идеальна для Ryzen 7000 серии.",
                            IsActive = true,
                            IsFeatured = false,
                            ManufacturerId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Name = "MSI MAG B650 TOMAHAWK WIFI",
                            Price = 389.00m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 98,
                            Sku = "MB-MSI-B650TOM",
                            Specifications = new Dictionary<string, object> { ["socket"] = "AM5", ["chipset"] = "B650", ["form_factor"] = "ATX", ["memory_slots"] = 4, ["max_memory"] = "128GB", ["memory_type"] = "DDR5", ["pcie_slots"] = "2x PCIe 4.0 x16", ["m2_slots"] = 4, ["usb_ports"] = "9x USB-A, 1x USB-C", ["wifi"] = "WiFi 6E", ["lan"] = "2.5G" },
                            Stock = 22,
                            WarrantyMonths = 36
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Комплект оперативной памяти Kingston FURY Beast 2x16GB DDR5-5600 MHz. CL36, 1.25V. Высокая производительность для игр и работы.",
                            IsActive = true,
                            IsFeatured = true,
                            ManufacturerId = new Guid("10000000-0000-0000-0000-000000000009"),
                            Name = "Kingston FURY Beast 32GB DDR5-5600",
                            OldPrice = 299.00m,
                            Price = 249.00m,
                            Rating = 4.7999999999999998,
                            ReviewCount = 203,
                            Sku = "RAM-KING-32D5",
                            Specifications = new Dictionary<string, object> { ["capacity"] = "32GB", ["kit_config"] = "2x16GB", ["type"] = "DDR5", ["speed"] = "5600 MHz", ["cas_latency"] = 36, ["voltage"] = "1.25V", ["heat_spreader"] = true, ["rgb"] = false },
                            Stock = 45,
                            WarrantyMonths = 36
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Память G.Skill Trident Z5 RGB 2x16GB DDR5-6000 MHz CL30. Эффектная RGB-подсветка, оптимизировано для Intel XMP 3.0.",
                            IsActive = true,
                            IsFeatured = true,
                            ManufacturerId = new Guid("10000000-0000-0000-0000-000000000011"),
                            Name = "G.Skill Trident Z5 RGB 32GB DDR5-6000",
                            Price = 329.00m,
                            Rating = 4.9000000000000004,
                            ReviewCount = 145,
                            Sku = "RAM-GSKILL-32Z5",
                            Specifications = new Dictionary<string, object> { ["capacity"] = "32GB", ["kit_config"] = "2x16GB", ["type"] = "DDR5", ["speed"] = "6000 MHz", ["cas_latency"] = 30, ["voltage"] = "1.35V", ["heat_spreader"] = true, ["rgb"] = true },
                            Stock = 30,
                            WarrantyMonths = 36
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Видеокарта Palit GeForce RTX 4070 SUPER 12GB GDDR6X. DLSS 3, Ray Tracing, 12GB VRAM. Отличная производительность в 1440p.",
                            IsActive = true,
                            IsFeatured = true,
                            ManufacturerId = new Guid("10000000-0000-0000-0000-000000000008"),
                            Name = "Palit GeForce RTX 4070 SUPER Dual",
                            Price = 2199.00m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 72,
                            Sku = "GPU-PALIT-4070S",
                            Specifications = new Dictionary<string, object> { ["gpu"] = "NVIDIA GeForce RTX 4070 SUPER", ["vram"] = "12GB GDDR6X", ["memory_bus"] = "192-bit", ["base_clock"] = "1980 MHz", ["boost_clock"] = "2475 MHz", ["cuda_cores"] = 7168, ["rt_cores"] = 56, ["tdp"] = "220W", ["outputs"] = "3x DisplayPort 1.4a, 1x HDMI 2.1", ["recommended_psu"] = "650W" },
                            Stock = 8,
                            WarrantyMonths = 36
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Видеокарта Gigabyte Radeon RX 7800 XT 16GB GDDR6. 16GB VRAM, FSR 3, отличное соотношение цена/производительность для 1440p.",
                            IsActive = true,
                            IsFeatured = false,
                            ManufacturerId = new Guid("10000000-0000-0000-0000-000000000005"),
                            Name = "Gigabyte Radeon RX 7800 XT GAMING OC",
                            Price = 1899.00m,
                            Rating = 4.5999999999999996,
                            ReviewCount = 58,
                            Sku = "GPU-GIGA-7800XT",
                            Specifications = new Dictionary<string, object> { ["gpu"] = "AMD Radeon RX 7800 XT", ["vram"] = "16GB GDDR6", ["memory_bus"] = "256-bit", ["base_clock"] = "1295 MHz", ["boost_clock"] = "2430 MHz", ["stream_processors"] = 3840, ["ray_accelerators"] = 60, ["tdp"] = "263W", ["outputs"] = "2x DisplayPort 2.1, 2x HDMI 2.1, 1x USB-C", ["recommended_psu"] = "700W" },
                            Stock = 14,
                            WarrantyMonths = 36
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000010"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Блок питания Corsair RM750e 750W, сертификат 80+ Gold, полностью модульный. Тихий 120mm вентилятор, ATX 3.0 совместимость.",
                            IsActive = true,
                            IsFeatured = true,
                            ManufacturerId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Name = "Corsair RM750e 750W 80+ Gold",
                            Price = 289.00m,
                            Rating = 4.7999999999999998,
                            ReviewCount = 189,
                            Sku = "PSU-CORS-RM750E",
                            Specifications = new Dictionary<string, object> { ["wattage"] = "750W", ["efficiency"] = "80+ Gold", ["modular"] = "Full", ["fan_size"] = "120mm", ["fan_type"] = "Rifle Bearing", ["atx_version"] = "ATX 3.0", ["pcie_connectors"] = "4x 8-pin (2x 12VHPWR)", ["sata_connectors"] = 8, ["noise_level"] = "10-25 dBA" },
                            Stock = 35,
                            WarrantyMonths = 60
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000011"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Блок питания be quiet! Pure Power 12 M 850W, 80+ Gold, полумодульный. Немецкая разработка, сверхтихая работа.",
                            IsActive = true,
                            IsFeatured = false,
                            ManufacturerId = new Guid("10000000-0000-0000-0000-000000000012"),
                            Name = "be quiet! Pure Power 12 M 850W",
                            Price = 319.00m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 156,
                            Sku = "PSU-BEQT-PP12M",
                            Specifications = new Dictionary<string, object> { ["wattage"] = "850W", ["efficiency"] = "80+ Gold", ["modular"] = "Semi", ["fan_size"] = "135mm", ["fan_type"] = "Silent Wings", ["atx_version"] = "ATX 3.0", ["pcie_connectors"] = "6x 8-pin", ["sata_connectors"] = 6, ["noise_level"] = "5-18 dBA" },
                            Stock = 20,
                            WarrantyMonths = 60
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000012"),
                            CategoryId = new Guid("00000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Блок питания Seasonic Focus GX-850 850W, 80+ Gold, полностью модульный. Премиум качество, 10 лет гарантии.",
                            IsActive = true,
                            IsFeatured = true,
                            ManufacturerId = new Guid("10000000-0000-0000-0000-000000000013"),
                            Name = "Seasonic Focus GX-850 850W",
                            Price = 349.00m,
                            Rating = 4.9000000000000004,
                            ReviewCount = 234,
                            Sku = "PSU-SEAS-GX850",
                            Specifications = new Dictionary<string, object> { ["wattage"] = "850W", ["efficiency"] = "80+ Gold", ["modular"] = "Full", ["fan_size"] = "120mm", ["fan_type"] = "Fluid Dynamic Bearing", ["atx_version"] = "ATX 3.0", ["pcie_connectors"] = "6x 8-pin", ["sata_connectors"] = 8, ["noise_level"] = "8-22 dBA" },
                            Stock = 18,
                            WarrantyMonths = 120
                        });
                });

            modelBuilder.Entity("CatalogService.Models.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AltText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alt_text");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("product_images", (string)null);
                });

            modelBuilder.Entity("CatalogService.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<string>("Cons")
                        .HasColumnType("text")
                        .HasColumnName("cons");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Helpful")
                        .HasColumnType("integer");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Pros")
                        .HasColumnType("text")
                        .HasColumnName("pros");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("CatalogService.Models.Category", b =>
                {
                    b.HasOne("CatalogService.Models.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("CatalogService.Models.CategoryFilterAttribute", b =>
                {
                    b.HasOne("CatalogService.Models.Category", "Category")
                        .WithMany("FilterAttributes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CatalogService.Models.Product", b =>
                {
                    b.HasOne("CatalogService.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CatalogService.Models.Manufacturer", "Manufacturer")
                        .WithMany("Products")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("CatalogService.Models.ProductImage", b =>
                {
                    b.HasOne("CatalogService.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CatalogService.Models.Review", b =>
                {
                    b.HasOne("CatalogService.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CatalogService.Models.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("FilterAttributes");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("CatalogService.Models.Manufacturer", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CatalogService.Models.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
