// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PCBuilderService.Data;

#nullable disable

namespace PCBuilderService.Migrations
{
    [DbContext(typeof(PCBuilderDbContext))]
    [Migration("20260401070207_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PCBuilderService.Models.PCConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<Guid?>("CoolerId")
                        .HasColumnType("uuid")
                        .HasColumnName("cooler_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("GpuId")
                        .HasColumnType("uuid")
                        .HasColumnName("gpu_id");

                    b.Property<bool>("IsCompatible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_compatible");

                    b.Property<Guid?>("MotherboardId")
                        .HasColumnType("uuid")
                        .HasColumnName("motherboard_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ProcessorId")
                        .HasColumnType("uuid")
                        .HasColumnName("processor_id");

                    b.Property<Guid?>("PsuId")
                        .HasColumnType("uuid")
                        .HasColumnName("psu_id");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("purpose");

                    b.Property<Guid?>("RamId")
                        .HasColumnType("uuid")
                        .HasColumnName("ram_id");

                    b.Property<string>("ShareToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("share_token");

                    b.Property<Guid?>("StorageId")
                        .HasColumnType("uuid")
                        .HasColumnName("storage_id");

                    b.Property<int>("TotalPower")
                        .HasColumnType("integer")
                        .HasColumnName("total_power");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_price");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ShareToken")
                        .HasFilter("share_token IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("pc_configurations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
