{{- if .Values.networkPolicy.defaultDeny -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "backend-service.fullname" . }}-default-deny
  labels:
    {{- include "backend-service.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "backend-service.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
{{- end }}
